export enum ActionEnum {
    /* Logs for resources */
    CREATE_RESOURCE = "CREATE_RESOURCE",
    READ_RESOURCE = "READ_RESOURCE",
    UPDATE_RESOURCE = "UPDATE_RESOURCE",
    DELETE_RESOURCE = "DELETE_RESOURCE",

    /* Logs for errors */
    VALIDATION_ERROR = "VALIDATION_ERROR",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
    DATABASE_ERROR = "DATABASE_ERROR",
    UNHANDLED_EXCEPTION = "UNHANDLED_EXCEPTION",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    PERMISSION_DENIED = "PERMISSION_DENIED"
}