CREATE TABLE AUDIT_LOGS (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ACTION TEXT NOT NULL,
    ACTOR TEXT NOT NULL,
    METADATA JSONB,
    RESOURCE TEXT NOT NULL,
    TIMESTAMP TIMESTAMP WITH TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);